language: objective-c
xcode_project: Kraftstoff.xcworkspace
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
osx_image: xcode9.1
cache:
- bundler
- cocoapods
#before_script:
#- "./scripts/install-swift.sh"
script:
- fastlane test
#env:
#  global:
#    - TOOLCHAINS=swift
