language: objective-c
osx_image: xcode7.3
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
cache:
- bundler
before_script:
- "./scripts/install-swift.sh"
script:
- fastlane test
env:
  global:
    - TOOLCHAINS=swift
