version: ~> 1.0
language: swift
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
osx_image: xcode12
cache:
- bundler
install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- brew bundle
before_script:
- "./scripts/add-key.sh"
script:
- bundle exec fastlane test
- bundle exec fastlane testMacOS
after_script:
- "./scripts/remove-key.sh"
addons:
  homebrew:
    brewfile: true
    # TODO: Remove the `update` line once this PR has been released:
    # https://github.com/travis-ci/packer-templates-mac/pull/13
    update: true
