language: objective-c
osx_image: xcode7.3
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
cache:
- bundler
before_script:
- brew update && brew upgrade xctool || true
- "./scripts/install-swift.sh"
script:
- set -o pipefail && xcodebuild -project Kraftstoff.xcodeproj -scheme Kraftstoff -sdk iphonesimulator build test | xcpretty
env:
  global:
    - TOOLCHAINS=swift
