version: ~> 1.0
language: objective-c
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
osx_image: xcode11.3
cache:
- bundler
#before_script:
#- "./scripts/install-swift.sh"
install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- brew bundle
script:
- bundle exec fastlane test
- bundle exec fastlane testMacOS
