language: objective-c
osx_image: xcode8
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
cache:
- bundler
#before_script:
#- "./scripts/install-swift.sh"
script:
# temporary workaround for Xcode 8 (see https://github.com/fastlane/fastlane/issues/5163)
- export PATH="$TRAVIS_BUILD_DIR/fastlane:$PATH"
- fastlane test
#env:
#  global:
#    - TOOLCHAINS=swift
