version: ~> 1.0
language: objective-c
xcode_project: Kraftstoff.xcodeproj
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
osx_image: xcode11.3
cache:
- bundler
#before_script:
#- "./scripts/install-swift.sh"
install:
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script:
- bundle exec fastlane test
- bundle exec fastlane testMacOS
addons:
  homebrew:
    brewfile: true
    # TODO: Remove the `update` line once this PR has been released:
    # https://github.com/travis-ci/packer-templates-mac/pull/13
    update: true
