language: objective-c
xcode_project: Kraftstoff.xcworkspace
xcode_scheme: Kraftstoff
xcode_sdk: iphonesimulator
osx_image: xcode10
cache:
- bundler
- cocoapods
#before_script:
#- "./scripts/install-swift.sh"
install: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script:
- fastlane test
