pool:
  vmImage: 'macOS 10.15'
variables:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
steps:
- script: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  displayName: 'Install gems'
- script: brew bundle
  displayName: 'Install homebrew dependencies'
- script: bundle exec fastlane test
  displayName: 'Build and test with fastlane'
- script: bundle exec fastlane testMacOS
  displayName: 'Build and test with fastlane'
