pool:
  vmImage: 'macOS 10.13'

steps:
- script: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  displayName: 'Install gems'
- script: brew bundle
  displayName: 'Install homebrew dependencies'
- script: ls -ld /Applications/Xcode*
  displayName: 'List Xcode versions'
- script: bundle exec fastlane test
  displayName: 'Build and test with fastlane'
