pool:
  vmImage: 'macOS 10.14'
variables:
  DEVELOPER_DIR: /Applications/Xcode_10.2.app
steps:
- script: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  displayName: 'Install gems'
- script: brew bundle
  displayName: 'Install homebrew dependencies'
- script: bundle exec fastlane test
  displayName: 'Build and test with fastlane'
