# vi: ft=ruby

# A list of devices you want to take the screenshots from
devices([
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone SE",
  "iPad Pro (9.7 inch)",
  "iPad Pro (12.9 inch)"
])

languages([
  "en-US",
  "de-DE",
  "fr-FR",
  "ja-JP"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "Kraftstoff UI Tests"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
