name: fastlane

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install gems
      run: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
    - name: Install homebrew dependencies
      run: brew bundle
    - name: Build and test (iOS)
      run: bundle exec fastlane test
    - name: Build and test (macOS)
      run: bundle exec fastlane testMacOS
