name: fastlane

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install homebrew dependencies
      run: brew bundle
    - name: Build and test
      run: fastlane test
