name: fastlane

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer

jobs:
  build:

    runs-on: macOS-11

    steps:
    - uses: actions/checkout@v2
    - name: Install gems
      run: bundle config set deployment 'true'; bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
    - name: Add key
      run: "./scripts/add-key.sh"
      env:
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    - name: Build and test (iOS)
      run: bundle exec fastlane test
    - name: Build and test (macOS)
      run: bundle exec fastlane testMacOS
    - name: Remove key
      run: "./scripts/remove-key.sh"
